name: ivim
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - joblib=0.17.0
  - matplotlib=3.3.2
  - nibabel=3.2.0
  - numpy=1.19.2
  - python=3.6.12
  - pytorch=1.4.0
  - scipy=1.5.2
  - torchvision=0.5.0
  - tqdm=4.50.2
